import {
  Stack,
  Card,
  Group,
  Badge,
  Text,
  Timeline,
  Code,
  Center,
} from '@mantine/core';
import { useReleases } from '../hook/useReleases';
import { changeType } from '../utils/parseReleases';

const typeColors: Record<string, string> = {
  feat: 'green',
  fix: 'red',
  refactor: 'blue',
  docs: 'grape',
  chore: 'gray',
  perf: 'orange',
  test: 'cyan',
  build: 'teal',
  ci: 'violet',
  other: 'dark',
};

export function ReleasesTab() {
  const { releases } = useReleases();

  if (releases.length === 0) {
    return (
      <Center h={300}>
        <Text c="dimmed">No releases yet. Deploy to gh-pages to create the first release entry.</Text>
      </Center>
    );
  }

  return (
    <Stack gap="md" p="md" maw={800} mx="auto">
      <Text size="lg" fw={600} c="yellow">
        Deployment Releases
      </Text>
      <Text size="sm" c="dimmed" mb="md">
        Each entry corresponds to a push to the <Code>gh-pages</Code> branch. Auto-generated by the deploy script.
      </Text>

      <Timeline active={releases.length - 1} bulletSize={32} lineWidth={2} color="yellow">
        {releases.map((release) => {
          const cType = changeType(release.message);
          const color = typeColors[cType] ?? 'dark';

          return (
            <Timeline.Item
              key={release.version}
              title={
                <Group gap="xs" align="center">
                  <Badge variant="filled" color="yellow" size="lg" radius="sm">
                    {release.version}
                  </Badge>
                  <Badge variant="light" color={color} size="sm">
                    {cType}
                  </Badge>
                  <Text size="sm" c="dimmed">
                    {release.date}
                  </Text>
                </Group>
              }
            >
              <Card shadow="xs" padding="sm" radius="md" withBorder>
                <Stack gap="xs">
                  <Text size="sm" fw={500}>
                    {release.message}
                  </Text>
                  <Group gap="md">
                    <Text size="xs" c="dimmed">
                      Commit: <Code>{release.commit}</Code>
                    </Text>
                    <Text size="xs" c="dimmed">
                      Author: {release.author}
                    </Text>
                  </Group>
                </Stack>
              </Card>
            </Timeline.Item>
          );
        })}
      </Timeline>
    </Stack>
  );
}
